Models/ClientInfoModel.cs
using System.Text.Json.Serialization;

namespace kithtokin_web.Models
{
    public class ClientInfoModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string WhatsAppNumber { get; set; }
        public string ContryOfResidence { get; set; }
        public string CityOfResidence { get; set; }
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public ResidenceTypeEnum ResidenceType { get; set; }
        public string? ResidentTypeOtherText { get; set; }
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public YearsAbroadEnum YearsAbroad { get; set; }
        public IList<LanguageEnum> Languages { get; set; }
        public IList<CommunicationMethodEnum> CommunicationMethods { get; set; }

        public IList<string> CallTime { get; set; }
        public IList<ServiceTypeEnum> ServiceTypes { get; set; }

    }
}

Models/CommunicationMethodEnum.cs
using System.Text.Json.Serialization;

namespace kithtokin_web.Models
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum CommunicationMethodEnum
    {
        Email = 0,
        WhatsApp_Text = 1,
        WhatsApp_Call = 2,
    }
}

Models/DBEntities/Client.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace kithtokin_web.Models.DBEntities
{
    public class Client
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }

        [StringLength(15)]
        public string WhatsAppNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string ContryOfResidence { get; set; }
        [Required]
        [StringLength(50)]
        public string CityOfResidence { get; set; }
        [Required]
        [StringLength(20)]
        public string ResidenceType { get; set; }

        [StringLength(100)]
        public string? OtherResidentType { get; set; }
        [StringLength(25)]
        public string YearsAbroad { get; set; }

        public ICollection<Service> Services { get; set; }
        
    }
}

Models/DBEntities/Service.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace kithtokin_web.Models.DBEntities
{
    public class Service
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        [Required]
        public string ServiceName {  get; set; }

        [Required]
        [StringLength(21)]
        public string Languages { get; set; }
        [Required]
        [StringLength(50)]
        public string CommunicationMethods { get; set; }
        [StringLength(256)]
        public string CallTime { get; set; }

        [ForeignKey("ClientId")]
        public Client Client { get; set; }
        [StringLength(11)]
        public string RequestID {  get; set; }
    }
}

Models/ErrorViewModel.cs
namespace kithtokin_web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LanguageEnum.cs
using System.Text.Json.Serialization;

namespace kithtokin_web.Models
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum LanguageEnum
    {
        English = 0,
        Sinhala = 1,
        Tamil = 2,
    }
}

Models/ResidenceTypeEnum.cs
namespace kithtokin_web.Models
{
    public enum ResidenceTypeEnum
    {
        Permanent = 0,
        Citizen = 1,
        Dual_Citizen = 2,
        Other = 3,
    }
}

Models/ServiceTypeEnum.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace kithtokin_web.Models
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ServiceTypeEnum
    {
        [Display(Name = "Family connection and care")]
        Family_connection_and_care = 0,
        [Display(Name = "Property maintenance")]
        Property_maintenance = 1,
        [Display(Name = "Holiday arrangements")]
        Holiday_arrangements = 2,
        [Display(Name = "Legal documentatio")]
        Legal_documentation = 3,
        [Display(Name = "Tasks at government departments")]
        Tasks_at_government_departments = 4,
        [Display(Name = "Social work")]
        Social_work = 5,
        [Display(Name = "A requirement specific to me")]
        A_requirement_specific_to_me = 6
    }
}

Models/UserInfoModel.cs
using System.Text.Json.Serialization;

namespace kithtokin_web.Models
{
    public class UserInfoModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string WhatsAppNumber { get; set; }
        public string ContryOfResidence { get; set; }
        public string CityOfResidence { get; set; }
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public ResidenceTypeEnum ResidenceType { get; set; }
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public YearsAbroadEnum YearsAbroad { get; set; }
        public IList<LanguageEnum> Languages { get; set; }
        public IList<CommunicationMethodEnum> CommunicationMethods { get; set; }

        public string CallTime { get; set; }
        public IList<ServiceTypeEnum> ServiceTypes { get; set; }

    }
}

Models/YearsAbroadEnum.cs
namespace kithtokin_web.Models
{
    public enum YearsAbroadEnum
    {
        Years_0_5 = 0,
        Years_5_10 = 1,
        Years_More_Than_10 = 2,

    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace kithtokin_web.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult WhoWeAre()
        {
            return Redirect(Url.Action("Index", "About") + "#who_we_are"); 
        }

        public IActionResult OurCommunity()
        {
            return Redirect(Url.Action("Index", "About") + "#our_community");
        }
    }
}

Controllers/ConnectionRequestController.cs
using kithtokin_web.BusinessLogicLayer;
using kithtokin_web.Models;
using Microsoft.AspNetCore.Mvc;
//using Newtonsoft.Json;
using System.Text.Json;

namespace kithtokin_web.Controllers
{
    public class ConnectionRequestController : Controller
    {
        private readonly IClientService _clientService;

        public ConnectionRequestController(IClientService clientService)
        {
            this._clientService = clientService;
        }
        public IActionResult Index()
        {
            return View();
        }

        
        [HttpPost]
        public IActionResult SaveFormData([FromBody] ClientInfoModel userInfo)
        {
            try
            {
                string confirmationId = _clientService.AddClientWithServiceData(userInfo);
                return Json(new { success = true, confirmationId = confirmationId, message = "Data saved successfully" });
            }
            catch (Exception e)
            {
                return Json(new { success = false, confirmationId = "0", message = "Could not save data", stack = e.InnerException?.ToString() });
            }
            
        }


    }
}
    

Controllers/HomeController.cs
using kithtokin_web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace kithtokin_web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace kithtokin_web.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/About/Index.cshtml
@{
    ViewData["Title"] = "About Page";
}

<section class="about">
    <div class="space"></div>
    <div class="row_about">
        <div class="col1_about">
            <img src="images\welcome_hands.png.png">
            <div class="box"></div>
        </div>
        <div class="col2_about">
            <!--<h3>About Us</h3><br>-->
            <p>
                There is an increasing trend of people leaving the country of origin to move to other countries
                around the world.
                This trend has been the same for Sri Lankans in the past and is quite regular recently due to the
                economical and political instability within the last few years.
                When the move occurs, people are often required to leave loved ones, wealth, and ongoing tasks
                behind resulting the need of support in the areas like,
            </p>
            <ul>
                <li>Family connection and care</li>
                <li>Property maintenance</li>
                <li>Holiday arrangements</li>
                <li>Legal documentation</li>
                <li>Tasks at government departments</li>
                <li>Social work</li>
            </ul>
            <br>
            <p>
                With the limited facilities, infrastructure and technology available in the country, addressing these
                requirements from a distance might be extremely complicated.
                <br><br>
                The need for a trustworthy service provider in Sri Lanka to address this complication is now more
                essential than ever. Here at KithtoKinLanka, our purpose is to provide this service that comforts
                like family, and is loyal like a friend.
            </p>
            <div class="box"></div>
        </div>
    </div>
</section>

<section class="vision">
    <h3>Vision</h3>
    <p>To help people live where they choose</p>
    <br>
    <h3>Mission</h3>
    <p>
        To help people with a Sri Lankan origin carry out living abroad with no worry about any responsibilities
        left behind.
    </p>
</section>

<section class="who">
    <div class="row_about">
        <div class="col_about">
            <h3 id="who_we_are">Who we are </h3>
            <br>
            <p>
                KithtoKinLanka (PVT) LTD, is a private limited company registered in Sri Lanka under the companies
                act No 07 of 2007. We provide service only within Sri Lanka for Sri Lankans living abroad.
            </p>
        </div>
        <div class="col_about">
            <img src="images\9whoweare.png">
        </div>
    </div>
</section>

<section class="community">
    <div class="row_about">
        <div class="col_about">
            <img src="images\img5.png">
        </div>
        <div class="col_about">
            <h3 id="our_community">Our Community </h3>
            <p>
                Our community comprises of everyone with a Sri Lankan origin. While we live anywhere in the world, we
                like to help each other. Helping others is a value in our culture.
                <br><br>
                Sri Lanka is rich in diversity, whether it is language, religion, culture, gender or even weather!
                Diversity is our wealth. KithtoKinLanka stands for respecting diversity.
                <br><br>
                KithtoKinLanka challenges the under-representation of some groups like women and people with
                disabilities in the Sri Lankan workforce. We give priority to all under-representated people and
                groups in our business.
                <br><br>
                We welcome support from anyone in the community to accomplish our mission while maintaining our
                values, that is, helping each other, inclusion and diversity.
            </p>
        </div>

    </div>
</section>

Views/ConnectionRequest/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@section Stylesheets {
    <link rel="stylesheet" href="css/connection-req-styles.css?v=@DateTime.Now">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/intlTelInput.css?v=@DateTime.Now">

}
@section Scripts {
    <script type="text/javascript" src="lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="js/phn_number/intlTelInput.js"></script>
    <script type="text/javascript" src="js/connection-request.js?v=@DateTime.Now"></script>
}



@{
    Html.RenderPartial("partials/_getting_started_modal");
}

<!-- MultiStep Form -->
@{
    Html.RenderPartial("partials/_multistep_form");
}

Views/ConnectionRequest/partials/_confirmation.cshtml
<fieldset>
    <div class="form-card">
        <div id="successConfirmDiv" style="display:none">
            <h2 class="fs-title text-center">Success !</h2>
            <p>Here is your confirmation number: <b><span id="confirmationNumber" style="color:black;"></span></b>. Please save this for future reference. You will also get a confirmation to your email.</p>
            <div class="slist">
                <h4>Next steps:</h4>
                <ol>
                    <li>We will reach out to you through your preffered communication method to discuss your requirements </li>
                    <br>
                    <li>
                        Mutually agree on the assignment (a service or services), assignment period, terms and conditions, cost
                        and payment plan
                    </li>
                    <br>
                    <li> We undertake the assignment while providing you with periodical updates</li>
                </ol>
            </div>
            <div class="row justify-content-center">
                <div class="alert alert-success" role="alert">
                    You have successfully submitted a connection request!
                </div>
            </div>
        </div>
        <div id="failConfirmDiv" style="display:none">
            <h2 class="fs-title text-center">Unable to send the request!</h2>
            <div>
               <p>We are unable to send your request right now. Please try again later. We apologies for the inconvinience.</p>
            </div>
            <div class="row justify-content-center">
                <div class="alert alert-danger" role="alert">
                    Connection request not sent!
                </div>
            </div>
        </div>
    </div>
</fieldset>

Views/ConnectionRequest/partials/_getting_started_modal.cshtml
<div class="modal" id="disclaimerModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Getting Started</h5>
                @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> *@
            </div>
            <div class="modal-body">
                <div class="slist">
                    <ol>
                        <li> You decide what you want to get done in Sri Lanka <br>(our <a asp-area="" asp-controller="Services" asp-action="Index">SERVICE</a> page will guide you) </li>
                        <br>
                        <li>You can connect with us by using the form on this page </li>
                        <br>
                        <li>We reach out to you through email or WhatsApp, as preferred by you, to discuss your requirements </li>
                        <br>
                        <li>
                            Mutually agree on the assignment (a service or services), assignment period, terms and conditions, cost
                            and payment plan
                        </li>
                        <br>
                        <li> We undertake the assignment while providing you with periodical updates</li>
                    </ol>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="agreeCheckbox">
                    <label class="form-check-label" for="agreeCheckbox">I understand.</label>
                </div>
                <div class="alert alert-danger" role="alert" id="alertModalError" style="display:none">
                    Please tick the 'I Understand' checkbox.
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="confirmButton">Confirm</button>
                <button type="button" class="btn btn-primary" id="modalBackBtn" onclick="history.back();">Back</button>
            </div>
        </div>
    </div>
</div>

Views/ConnectionRequest/partials/_multistep_form.cshtml
<div class="container-fluid" id="grad1">
    <div class="row justify-content-center mt-0">
        <div class="col-11 col-sm-9 col-md-7 col-lg-6 text-center p-0 mb-2" style="margin-top:130px">
            <div class="card px-0 pt-4 pb-0 mt-3 mb-3">
                <h2><strong>Connection Request Form</strong></h2>
                <p>All the entries with a star mark (<b style="color:red">*</b>) are mandatory for a successful submission of a request. </p>
                <div class="row">
                    <div class="col-md-12 mx-0">
                        <form id="msform">
                            <!-- progressbar -->
                            <ul id="progressbar" style="margin-left:-25px">
                                <li class="active" id="profile"><strong>Profile Info.</strong></li>
                                <li id="serviceinfo"><strong>Service Info. </strong></li>
                                <li id="confirm"><strong>Finish</strong></li>
                            </ul>
                            <!-- fieldsets -->
                            @{
                                Html.RenderPartial("partials/_profile_fields");
                            }
                            @{
                                Html.RenderPartial("partials/_service_info_fields");
                            }
                            @{
                                Html.RenderPartial("partials/_confirmation");
                            }
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/ConnectionRequest/partials/_profile_fields.cshtml
<fieldset id="profileFields">
    <div class="form-card">
        <h2 class="fs-title">Profile Information</h2>
        <ol>
            <li>
            <label>Name <span style="color: rgba(253, 6, 56, 0.86);"> *</span></label>
            <input type="text" name="name" id="cname" required>
            <span id="cnamevalidationError" class="validation-error-text"><i>Please enter your name.</i></span>
            </li>
            <li>
            <label>Email address<span style="color: rgba(253, 6, 56, 0.86);"> *</span></label>
            <input type="email" name="email" id="cemail" required>
            <span id="cemailvalidationError" class="validation-error-text"><i>Please enter a valid email.</i></span>
            </li>
            <li>
            <label>WhatsApp number</label>
            @* <input type="text" id="cwhatsapp"> *@
            <p id="output">Please enter a valid number below</p>
            <input id="phone" type="tel" style="padding-right:6px;padding-left:52px;margin-left:0;"><br><br>
            </li>
            <li>
            <label>Country of Current Residence <span style="color: rgba(253, 6, 56, 0.86);"> *</span></label>
            <!-- Country names and Country Name -->
                @{
                    Html.RenderPartial("partials/_countries_dropdown");
                }<br>
            <span id="resCountryvalidationError" class="validation-error-text"><i>Please select a country.</i></span>
            </li>
            <li>
            <label>City of Current Residence</label>
            <input type="text" id="crescity">
            <span id="resCityvalidationError" class="validation-error-text"><i>Please enter a city.</i></span>
            </li>
            <li>
            <label>
                Residence Type (Permanent, Citizen, Dual Citizen etc.)<span style="color: rgba(253, 6, 56, 0.86);">
                    *
                </span>
            </label>
            <div style="margin-top:5px;">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="crestype" id="permanentRes" value="Permanent" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="permanentRes">Permanent Resident</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="crestype" id="citizen" value="Citizen" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="citizen">Citizen</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="crestype" id="dual_citizen" value="Dual_Citizen" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="dual_citizen">Dual Citizen</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="crestype" id="other_resident" value="Other" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="other_resident">Other</label>
                </div>
                <div class="form-check" id="otherRestypeDiv" style="display:none">
                    <label class="form-check-label" for="other_resident">Please enter the Residence Type</label>
                    <input type="text" name="otherResTypeInputText" id="otherResTypeInputText" maxlength="15">
                    <span id="otherResTypeValidationError" class="validation-error-text"><i>This field cannot be empty.</i></span>
                </div>
            </div>
            <span id="resTypeValidationError" class="validation-error-text"><i>Please select a Residence Type.</i></span>
            </li>
            <li>
            <label>How many years have you been abroad?</label>
            <div style="margin-top:5px;">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="durationOption" id="y0_5" value="Years_0_5" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="y0_5">0-5 Years</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="durationOption" id="y5_10" value="Years_5_10" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="y5_10">5-10 Years</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="durationOption" id="y10above" value="Years_More_Than_10" style="width:auto;border-radius:5px;border:1px solid lightgrey">
                    <label class="form-check-label" for="y10above">More than 10 Years</label>
                </div>
            </div>
            <span id="rearsAbroadValidationError" class="validation-error-text"><i>Please select one of the options.</i></span>
            </li>
        </ol>
    </div>
    <input type="button" name="next" id="on_profile_next" class="next action-button" value="Next" />
</fieldset>

Views/Services/Index.cshtml
@{
    ViewData["Title"] = "Service Page";
}


<section class="services">
    <br>
    <a><strong>Do you require support to get anything related to the following categories done in Sri Lanka?</strong></a>
    <div class="row">
        <div class="col">
            <img src="images\img1.png">
            <div class="layer">
                <h3>Family connection and care</h3>
            </div>
            <!--<div class="desc_service"> Family connection and care</div>-->
        </div>
        <div class="col">
            <img src="images\img2.png">
            <div class="layer">
                <h3>Property maintenance</h3>
            </div>
            <!--<div class="desc_service"> Property maintenance</div>-->
        </div>
        <div class="col">
            <img src="images\img3.png">
            <div class="layer">
                <h3>Holiday arrangements</h3>
            </div>
            <!--<div class="desc_service"> Holiday arrangements</div>-->
        </div>
    </div>
    <div class="row">
        <div class="col">
            <!--<div class="desc_service"> Legal documentation</div>-->
            <img src="images\img8.png">
            <div class="layer">
                <h3>Legal documentation</h3>
            </div>
        </div>
        <div class="col">
            <!--<div class="desc_service"> Tasks at government departments</div>-->
            <img src="images\img15.jpg">
            <div class="layer">
                <h3>Tasks at government departments</h3>
            </div>
        </div>
        <div class="col">
            <!--<div class="desc_service"> Social work</div>-->
            <img src="images\img11.png">
            <div class="layer">
                <h3>Social work</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <img src="images\img9.png" style="display: none;">
        </div>
        <div class="col">
            <img src="images\img9.png">
            <div class="layer" style="background: rgba(10, 128, 154, 0.9);">
                <a>
                    <h3 style="opacity: 1; bottom: 49%;">A requirement specific to you</h3>
                </a>
            </div>
        </div>
        <div class="col">
            <img src="images\img9.png" style="display: none;">
        </div>
    </div>
</section>

<section class="desc" id="redirect">
    <p>You can obtain the service of KithToKinLanka by sending a   <a class="btn" href="Connection.html"><strong>CONNECTION REQUEST</strong></a></p>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] kithtokinlanka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/kithtokin_web.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="css/swiper-bundle.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Display:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,600;1,700;1,900&display=swap"
          rel="stylesheet">
    @RenderSection("Stylesheets", required:false)
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar-container container">
                <input type="checkbox" name="" id="">
                <div class="hamburger-lines">
                    <span class="line line1"></span>
                    <span class="line line2"></span>
                    <span class="line line3"></span>
                </div>
                <ul class="menu-items">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="About" asp-action="Index">ABOUT</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Services" asp-action="Index">SERVICE</a>
                    </li>
                    <li>
                        <a class="btn-con-request" asp-area="" asp-controller="ConnectionRequest" asp-action="Index">CONNECTION REQUEST</a>
                    </li>
                </ul>
                <div class="logo"><a class="logo" href="index.html"><img src="images\logotransparent.png"></a></div>
                <div class="logo2"><img src="images\Asset 2.png"></div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <section class="contact">
            <div class="contact_row">
                <div class="contact_col">
                    <address>
                        <a asp-area="" asp-controller="About" asp-action="WhoWeAre">Who we are</a> <br>
                        <a asp-area="" asp-controller="About" asp-action="OurCommunity">Our Community</a> <br>
                        <a href="DataPolicy.html">Data Protection Policy </a> <br>
                    </address>
                </div>
                <div class="contact_col">
                    <h3>Contact Us</h3>
                    <address>
                        <!--Text messages: whatsapp number<br>-->
                        <b>Email:</b>
                        support@kithtokinlanka.com
                    </address>
                </div>
            </div>
            <div class="allrt">
                <p>All rights reserved with KithtoKinLanka (PVT) LTD, Sri Lanka (PV00278642)</p>
            </div>
        </section>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>